version: "3.7"
services:
  app:
      build:
        args:
          user: aji
          uid: 1000
        context: ./
        dockerfile: ./Dockerfile
      image: nusa
      container_name: nusa-app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
        - ./user.ini:/usr/local/etc/php/php.ini
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
      networks:
        - nusa
  nginx:
    image: nginx:1.17-alpine
    container_name: nusa-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      - nusa
  db:
    image: mariadb:latest
    container_name: nusa-db
    ports:
      - 3306:3306
    volumes:
      - nusadb:/var/lib/mysql
      - ./database:/database
    environment:
      MYSQL_ROOT_PASSWORD: password
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      nusa:
        ipv4_address: 10.5.0.99
  nodejs:
    image: node:16-alpine
    container_name: nusa-node
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ["npm","run", "dev"]
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      nusa:
        ipv4_address: 10.5.0.100

volumes:
  nusadb: 
    driver: local

networks:
  nusa:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.5.0.0/24
            gateway: 10.5.0.1
